title: Plugin Builder Tool
description: Python command line tool for compiling and deploying QGIS plugins
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
